# Generated by Django 5.2 on 2026-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='edat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
