# Generated by Django 5.2 on 2026-02-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0002_jugador_edat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='futbol.partit'),
        ),
    ]
